In [74]:
import pandas as pd
import numpy as np
import requests

## Импорты, задание формата и считывание

In [75]:
pd.options.display.float_format = '{:.2f}'.format

In [76]:
auto_ex02 = pd.read_json("auto.json")

In [77]:
auto_ex02

        CarNumber  Refund    Fines    Make    Model
0    Y163O8161RUS       2  3200.00    Ford    Focus
1     E432XX77RUS       1  6500.00  Toyota    Camry
2     7184TT36RUS       1  2100.00    Ford    Focus
3    X582HE161RUS       2  2000.00    Ford    Focus
4    92918M178RUS       1  5700.00    Ford    Focus
..            ...     ...      ...     ...      ...
720  Y163O8161RUS       2  1600.00    Ford    Focus
721  M0309X197RUS       1 22300.00    Ford    Focus
722  O673E8197RUS       2   600.00    Ford    Focus
723  8610T8154RUS       1  2000.00    Ford    Focus
724  H419XE197RUS       2  8594.59  Toyota  Corolla

[725 rows x 5 columns]

In [78]:
auto_ex02

        CarNumber  Refund    Fines    Make    Model
0    Y163O8161RUS       2  3200.00    Ford    Focus
1     E432XX77RUS       1  6500.00  Toyota    Camry
2     7184TT36RUS       1  2100.00    Ford    Focus
3    X582HE161RUS       2  2000.00    Ford    Focus
4    92918M178RUS       1  5700.00    Ford    Focus
..            ...     ...      ...     ...      ...
720  Y163O8161RUS       2  1600.00    Ford    Focus
721  M0309X197RUS       1 22300.00    Ford    Focus
722  O673E8197RUS       2   600.00    Ford    Focus
723  8610T8154RUS       1  2000.00    Ford    Focus
724  H419XE197RUS       2  8594.59  Toyota  Corolla

[725 rows x 5 columns]

In [79]:
np.random.seed(21)

## Дополнение рандомными значениями

In [80]:
sample = auto_ex02.sample(n=200, random_state=21)
refund_values = auto_ex02['Refund'].dropna().unique()
fines_values = auto_ex02['Fines'].dropna().unique()
sample['Refund'] = np.random.choice(refund_values, size=200)
sample['Fines'] = np.random.choice(fines_values, size=200)
concat_rows = pd.concat([auto_ex02, sample], ignore_index=True)

In [81]:
concat_rows

        CarNumber  Refund    Fines        Make   Model
0    Y163O8161RUS       2  3200.00        Ford   Focus
1     E432XX77RUS       1  6500.00      Toyota   Camry
2     7184TT36RUS       1  2100.00        Ford   Focus
3    X582HE161RUS       2  2000.00        Ford   Focus
4    92918M178RUS       1  5700.00        Ford   Focus
..            ...     ...      ...         ...     ...
920  8182XX154RUS       2 67200.00        Ford   Focus
921   X796TH96RUS       2  1100.00        Ford   Focus
922  T011MY163RUS       1 20600.00        Ford   Focus
923   T341CC96RUS       1  5500.00  Volkswagen  Passat
924   T119CT96RUS       2  2400.00        Ford   Focus

[925 rows x 5 columns]

In [82]:
years = np.random.randint(1980, 2020, size=len(concat_rows))
year_series = pd.Series(years, name='Year')
concat_rows['Year'] = year_series
fines = concat_rows

In [83]:
fines

        CarNumber  Refund    Fines        Make   Model  Year
0    Y163O8161RUS       2  3200.00        Ford   Focus  2006
1     E432XX77RUS       1  6500.00      Toyota   Camry  2019
2     7184TT36RUS       1  2100.00        Ford   Focus  1983
3    X582HE161RUS       2  2000.00        Ford   Focus  2009
4    92918M178RUS       1  5700.00        Ford   Focus  1989
..            ...     ...      ...         ...     ...   ...
920  8182XX154RUS       2 67200.00        Ford   Focus  2012
921   X796TH96RUS       2  1100.00        Ford   Focus  1985
922  T011MY163RUS       1 20600.00        Ford   Focus  2016
923   T341CC96RUS       1  5500.00  Volkswagen  Passat  2006
924   T119CT96RUS       2  2400.00        Ford   Focus  1990

[925 rows x 6 columns]

In [84]:
print(fines.columns)

Index(['CarNumber', 'Refund', 'Fines', 'Make', 'Model', 'Year'], dtype='str')

In [85]:
with open("surname.json", "r") as f:
    surnames = [x.split(",")[0].strip("[").strip("\"") for x in f.readlines()[1:]]
print(surnames)

['ADAMS', 'ALLEN', 'ALVAREZ', 'ANDERSON', 'BAILEY', 'BAKER', 'BENNETT', 'BROOKS', 'BROWN', 'CAMPBELL', 'CARTER', 'CASTILLO', 'CHAVEZ', 'CLARK', 'COLLINS', 'COOK', 'COOPER', 'COX', 'CRUZ', 'DAVIS', 'DIAZ', 'EDWARDS', 'EVANS', 'FLORES', 'FOSTER', 'GARCIA', 'GOMEZ', 'GONZALEZ', 'GRAY', 'GREEN', 'GUTIERREZ', 'HALL', 'HARRIS', 'HERNANDEZ', 'HILL', 'HOWARD', 'HUGHES', 'JACKSON', 'JAMES', 'JIMENEZ', 'JOHNSON', 'JONES', 'KELLY', 'KIM', 'KING', 'LEE', 'LEWIS', 'LONG', 'LOPEZ', 'MARTIN', 'MARTINEZ', 'MENDOZA', 'MILLER', 'MITCHELL', 'MOORE', 'MORALES', 'MORGAN', 'MORRIS', 'MURPHY', 'MYERS', 'NELSON', 'NGUYEN', 'ORTIZ', 'PARKER', 'PATEL', 'PEREZ', 'PETERSON', 'PHILLIPS', 'PRICE', 'RAMIREZ', 'RAMOS', 'REED', 'REYES', 'RICHARDSON', 'RIVERA', 'ROBERTS', 'ROBINSON', 'RODRIGUEZ', 'ROGERS', 'ROSS', 'RUIZ', 'SANCHEZ', 'SANDERS', 'SCOTT', 'SMITH', 'STEWART', 'TAYLOR', 'THOMAS', 'THOMPSON', 'TORRES', 'TURNER', 'WALKER', 'WARD', 'WATSON', 'WHITE', 'WILLIAMS', 'WILSON', 'WOOD', 'WRIGHT', 'YOUNG']

In [86]:
num_cars = 100  # например, 100 машин
car_numbers = [f"ABC{str(i).zfill(3)}" for i in range(1, num_cars + 1)]

# Создаем случайные фамилии без спецсимволов, равное количеству уникальных номеров
surnames_unique = np.random.choice(surnames, size=num_cars, replace=False)

# Создаем DataFrame
owners = pd.DataFrame({
    'CarNumber': car_numbers,
    'SURNAME': surnames_unique
})

In [87]:
owners

   CarNumber    SURNAME
0     ABC001   CASTILLO
1     ABC002       REED
2     ABC003      ALLEN
3     ABC004       DIAZ
4     ABC005     NELSON
..       ...        ...
95    ABC096  HERNANDEZ
96    ABC097     GARCIA
97    ABC098     WRIGHT
98    ABC099      PATEL
99    ABC100     WALKER

[100 rows x 2 columns]

In [88]:
# Создаем новые строки
new_rows = pd.DataFrame({
    'CarNumber': ['QW12345', 'ZX67890', 'ER23456', 'TY78901', 'UI34567'],
    'Refund': [1.5, 2.0, 0.5, 3.0, 1.0],
    'Fines': [1500, 3000, 500, 2000, 1000],
    'Make': ['Honda', 'Nissan', 'Mazda', 'Hyundai', 'Kia'],
    'Model': ['Civic', 'Sentra', '3', 'Elantra', 'Soul'],
    'Year': [2007, 2006, 2005, 1998, 2000]
})

# Объединяем с concat_rows
fines = pd.concat([fines, new_rows], ignore_index=True)

In [89]:
fines

        CarNumber  Refund   Fines     Make    Model  Year
0    Y163O8161RUS    2.00 3200.00     Ford    Focus  2006
1     E432XX77RUS    1.00 6500.00   Toyota    Camry  2019
2     7184TT36RUS    1.00 2100.00     Ford    Focus  1983
3    X582HE161RUS    2.00 2000.00     Ford    Focus  2009
4    92918M178RUS    1.00 5700.00     Ford    Focus  1989
..            ...     ...     ...      ...      ...   ...
925       QW12345    1.50 1500.00    Honda    Civic  2007
926       ZX67890    2.00 3000.00   Nissan   Sentra  2006
927       ER23456    0.50  500.00    Mazda        3  2005
928       TY78901    3.00 2000.00  Hyundai  Elantra  1998
929       UI34567    1.00 1000.00      Kia     Soul  2000

[930 rows x 6 columns]

In [90]:
print(fines.columns)

Index(['CarNumber', 'Refund', 'Fines', 'Make', 'Model', 'Year'], dtype='str')

In [91]:
owners = owners[:-20]

# 2. Создаем три новых наблюдения
new_owners = pd.DataFrame({
    'SURNAME': ['Ivan', 'Anna', 'Sergey'],
    'CarNumber': ['AB12345', 'CD67890', 'EF23456']
    # Добавьте другие колонки, если есть, и заполните их
})

# 3. Добавляем новые наблюдения в owners
owners = pd.concat([owners, new_owners], ignore_index=True)

In [92]:
owners

   CarNumber   SURNAME
0     ABC001  CASTILLO
1     ABC002      REED
2     ABC003     ALLEN
3     ABC004      DIAZ
4     ABC005    NELSON
..       ...       ...
78    ABC079     REYES
79    ABC080    MORRIS
80   AB12345      Ivan
81   CD67890      Anna
82   EF23456    Sergey

[83 rows x 2 columns]

## Слияние таблиц, проверки и сводная таблица

In [93]:
merged_both = pd.merge(fines, owners, left_on='CarNumber', right_on='CarNumber', how='inner')

In [94]:
merged_both

Empty DataFrame
Columns: [CarNumber, Refund, Fines, Make, Model, Year, SURNAME]
Index: []

In [95]:
all_cars = pd.merge(fines, owners, on='CarNumber', how='outer')

In [96]:
all_cars

         CarNumber  Refund    Fines    Make   Model    Year SURNAME
0     704687163RUS    2.00  1400.00    Ford   Focus 1993.00     NaN
1     704787163RUS    2.00  2800.00    Ford   Focus 1987.00     NaN
2     704987163RUS    2.00  8594.59    Ford   Focus 2007.00     NaN
3     705287163RUS    2.00  2000.00    Ford   Focus 2011.00     NaN
4     705387163RUS    2.00   700.00    Ford   Focus 1994.00     NaN
...            ...     ...      ...     ...     ...     ...     ...
1008  Y973O8197RUS    1.00 34800.00    Ford   Focus 2008.00     NaN
1009  Y973O8197RUS    1.00 69600.00    Ford   Focus 2000.00     NaN
1010  Y973O8197RUS    2.00  6900.00    Ford   Focus 1990.00     NaN
1011  Y973O8197RUS    2.00  6500.00    Ford   Focus 2018.00     NaN
1012       ZX67890    2.00  3000.00  Nissan  Sentra 2006.00     NaN

[1013 rows x 7 columns]

In [97]:
fines_only = fines[['CarNumber']]

In [98]:
fines_only

        CarNumber
0    Y163O8161RUS
1     E432XX77RUS
2     7184TT36RUS
3    X582HE161RUS
4    92918M178RUS
..            ...
925       QW12345
926       ZX67890
927       ER23456
928       TY78901
929       UI34567

[930 rows x 1 columns]

In [99]:
owners_only = owners[['CarNumber']]

In [100]:
owners_only

   CarNumber
0     ABC001
1     ABC002
2     ABC003
3     ABC004
4     ABC005
..       ...
78    ABC079
79    ABC080
80   AB12345
81   CD67890
82   EF23456

[83 rows x 1 columns]

In [101]:
fines

        CarNumber  Refund   Fines     Make    Model  Year
0    Y163O8161RUS    2.00 3200.00     Ford    Focus  2006
1     E432XX77RUS    1.00 6500.00   Toyota    Camry  2019
2     7184TT36RUS    1.00 2100.00     Ford    Focus  1983
3    X582HE161RUS    2.00 2000.00     Ford    Focus  2009
4    92918M178RUS    1.00 5700.00     Ford    Focus  1989
..            ...     ...     ...      ...      ...   ...
925       QW12345    1.50 1500.00    Honda    Civic  2007
926       ZX67890    2.00 3000.00   Nissan   Sentra  2006
927       ER23456    0.50  500.00    Mazda        3  2005
928       TY78901    3.00 2000.00  Hyundai  Elantra  1998
929       UI34567    1.00 1000.00      Kia     Soul  2000

[930 rows x 6 columns]

In [102]:
print(fines.columns)

Index(['CarNumber', 'Refund', 'Fines', 'Make', 'Model', 'Year'], dtype='str')

In [103]:
# Группируем по марке, модели и году, считаем сумму штрафов
grouped = fines.groupby(['Make', 'Model', 'Year'])['Fines'].sum().reset_index()

# Создаем таблицу с уровнем модели и маркой, а годы как колонки
pivot_table = grouped.pivot_table(
    index=['Make', 'Model'],
    columns='Year',
    values='Fines',
    aggfunc='sum'
)

In [104]:
pivot_table

Year                    1980     1981      1982      1983      1984      1985  \
Make       Model
Audi                     NaN      NaN       NaN       NaN       NaN       NaN
BMW                      NaN      NaN       NaN       NaN       NaN       NaN
Ford       Focus   105594.59 61089.17 319800.00 134100.00 199900.00 407394.59
           Mondeo        NaN      NaN       NaN       NaN       NaN       NaN
Honda      Civic         NaN      NaN       NaN       NaN       NaN       NaN
Hyundai    Elantra       NaN      NaN       NaN       NaN       NaN       NaN
Kia        Soul          NaN      NaN       NaN       NaN       NaN       NaN
Mazda      3             NaN      NaN       NaN       NaN       NaN       NaN
Nissan     Sentra        NaN      NaN       NaN       NaN       NaN       NaN
Skoda      Octavia       NaN 34700.00       NaN  24594.59   8500.00  14300.00
Toyota     Camry         NaN      NaN       NaN       NaN  21594.59       NaN
           Corolla  37800.00      NaN   2000.00  29000.00       NaN       NaN
Volkswagen               NaN      NaN       NaN       NaN       NaN   7400.00
           Golf       400.00   300.00  20800.00       NaN       NaN  37800.00
           Jetta         NaN      NaN       NaN       NaN   1000.00       NaN
           Passat    9100.00  7600.00  45600.00       NaN       NaN       NaN
           Touareg       NaN      NaN       NaN       NaN       NaN       NaN
Volvo                    NaN      NaN       NaN       NaN       NaN       NaN

Year                    1986      1987      1988      1989  ...      2010  \
Make       Model                                            ...
Audi                     NaN       NaN       NaN   3100.00  ...       NaN
BMW                      NaN       NaN       NaN       NaN  ...       NaN
Ford       Focus   364094.59 243994.59 203889.17 144300.00  ... 117589.17
           Mondeo    8600.00       NaN       NaN       NaN  ...       NaN
Honda      Civic         NaN       NaN       NaN       NaN  ...       NaN
Hyundai    Elantra       NaN       NaN       NaN       NaN  ...       NaN
Kia        Soul          NaN       NaN       NaN       NaN  ...       NaN
Mazda      3             NaN       NaN       NaN       NaN  ...       NaN
Nissan     Sentra        NaN       NaN       NaN       NaN  ...       NaN
Skoda      Octavia       NaN 150800.00       NaN   5900.00  ...   5800.00
Toyota     Camry    34000.00   1000.00       NaN       NaN  ...       NaN
           Corolla  34300.00       NaN  18900.00   4000.00  ...       NaN
Volkswagen               NaN       NaN       NaN       NaN  ...       NaN
           Golf          NaN   9300.00       NaN  24200.00  ...   1000.00
           Jetta         NaN   9000.00       NaN       NaN  ...       NaN
           Passat        NaN       NaN       NaN       NaN  ...       NaN
           Touareg       NaN       NaN       NaN       NaN  ...       NaN
Volvo                    NaN       NaN       NaN       NaN  ...       NaN

Year                    2011      2012      2013      2014      2015  \
Make       Model
Audi                     NaN       NaN       NaN       NaN       NaN
BMW                      NaN       NaN       NaN       NaN       NaN
Ford       Focus   123989.17 271394.59 300389.17 201400.00 283994.59
           Mondeo        NaN       NaN       NaN       NaN       NaN
Honda      Civic         NaN       NaN       NaN       NaN       NaN
Hyundai    Elantra       NaN       NaN       NaN       NaN       NaN
Kia        Soul          NaN       NaN       NaN       NaN       NaN
Mazda      3             NaN       NaN       NaN       NaN       NaN
Nissan     Sentra        NaN       NaN       NaN       NaN       NaN
Skoda      Octavia   4900.00   8594.59   2000.00    800.00       NaN
Toyota     Camry      500.00   3400.00  19800.00       NaN       NaN
           Corolla   5300.00       NaN  16000.00  36000.00       NaN
Volkswagen               NaN       NaN       NaN       NaN       NaN
           Golf       300.00       NaN       NaN       NaN  10600.00
           Jetta         NaN       NaN       NaN       NaN       NaN
           Passat    1900.00       NaN   3000.00   9500.00       NaN
           Touareg       NaN       NaN       NaN       NaN       NaN
Volvo                6800.00       NaN       NaN       NaN       NaN

Year                    2016      2017      2018     2019
Make       Model
Audi                 4200.00       NaN       NaN      NaN
BMW                      NaN       NaN       NaN      NaN
Ford       Focus   227783.76 232989.17 100194.59 76200.00
           Mondeo        NaN       NaN       NaN      NaN
Honda      Civic         NaN       NaN       NaN      NaN
Hyundai    Elantra       NaN       NaN       NaN      NaN
Kia        Soul          NaN       NaN       NaN      NaN
Mazda      3             NaN       NaN       NaN      NaN
Nissan     Sentra        NaN       NaN       NaN      NaN
Skoda      Octavia   2600.00   9594.59    600.00 39100.00
Toyota     Camry         NaN       NaN       NaN  6500.00
           Corolla       NaN       NaN   6800.00  3200.00
Volkswagen               NaN       NaN       NaN      NaN
           Golf          NaN       NaN   4600.00      NaN
           Jetta         NaN  53000.00       NaN  1600.00
           Passat        NaN       NaN   9900.00 34400.00
           Touareg       NaN       NaN       NaN  1300.00
Volvo               10200.00       NaN       NaN      NaN

[18 rows x 40 columns]

In [105]:
fines

        CarNumber  Refund   Fines     Make    Model  Year
0    Y163O8161RUS    2.00 3200.00     Ford    Focus  2006
1     E432XX77RUS    1.00 6500.00   Toyota    Camry  2019
2     7184TT36RUS    1.00 2100.00     Ford    Focus  1983
3    X582HE161RUS    2.00 2000.00     Ford    Focus  2009
4    92918M178RUS    1.00 5700.00     Ford    Focus  1989
..            ...     ...     ...      ...      ...   ...
925       QW12345    1.50 1500.00    Honda    Civic  2007
926       ZX67890    2.00 3000.00   Nissan   Sentra  2006
927       ER23456    0.50  500.00    Mazda        3  2005
928       TY78901    3.00 2000.00  Hyundai  Elantra  1998
929       UI34567    1.00 1000.00      Kia     Soul  2000

[930 rows x 6 columns]

In [106]:
owners

   CarNumber   SURNAME
0     ABC001  CASTILLO
1     ABC002      REED
2     ABC003     ALLEN
3     ABC004      DIAZ
4     ABC005    NELSON
..       ...       ...
78    ABC079     REYES
79    ABC080    MORRIS
80   AB12345      Ivan
81   CD67890      Anna
82   EF23456    Sergey

[83 rows x 2 columns]

In [107]:
fines.to_csv('fines.csv', index=False)
owners.to_csv('owners.csv', index=False)

In [108]:
concat_rows.count()

CarNumber    925
Refund       925
Fines        925
Make         925
Model        925
Year         925
dtype: int64

In [109]:
fines.count()

CarNumber    930
Refund       930
Fines        930
Make         930
Model        930
Year         930
dtype: int64

In [110]:
len(owners)

83

In [111]:
len(fines)

930