In [11]:
import pandas as pd

## Импортировал модуль pandas, считывание csv-файла

In [12]:
df = pd.read_csv(
    'feed-views.log',
    sep='\t',             # разделитель табуляция
    skiprows=[2, 3],      # пропускаем 3-ю и 4-ю строки (индексы 2 и 3)
    skipfooter=2,         # пропускаем последние две строки
    names=['datetime', 'user'],  # задаем имена колонок
    index_col='datetime',        # делаем datetime индексом
    engine='python'
)
# Переименование колонки index
df.index.name = 'date_time'

# Сохранение с разделителем ';'
df.to_csv('feed-views-semicolon.log', sep=';')
df

                                 user
date_time
2020-04-17 12:01:08.463179      artem
2020-04-17 12:01:23.743946      artem
2020-04-17 12:35:52.735016      artem
2020-04-17 12:36:21.401412     oksana
2020-04-17 12:36:22.023355     oksana
...                               ...
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

[1072 rows x 1 columns]

## Проверки

In [13]:
df.head()

                              user
date_time
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [14]:
df.tail()

                                 user
date_time
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

In [15]:
df.count()

user    1072
dtype: int64

In [16]:
new_df = pd.read_csv("feed-views-semicolon.log")
new_df

                            date_time;user
0         2020-04-17 12:01:08.463179;artem
1         2020-04-17 12:01:23.743946;artem
2         2020-04-17 12:35:52.735016;artem
3        2020-04-17 12:36:21.401412;oksana
4        2020-04-17 12:36:22.023355;oksana
...                                    ...
1067  2020-05-21 16:36:40.915488;ekaterina
1068      2020-05-21 17:49:36.429237;maxim
1069  2020-05-21 18:45:20.441142;valentina
1070      2020-05-21 23:03:06.457819;maxim
1071      2020-05-21 23:23:49.995349;pavel

[1072 rows x 1 columns]

In [17]:
new_df.head()

                      date_time;user
0   2020-04-17 12:01:08.463179;artem
1   2020-04-17 12:01:23.743946;artem
2   2020-04-17 12:35:52.735016;artem
3  2020-04-17 12:36:21.401412;oksana
4  2020-04-17 12:36:22.023355;oksana