In [183]:
import pandas as pd
import gc

## Импорт и считывание

In [184]:
df = pd.read_csv("fines.csv")
df

        CarNumber  Refund   Fines     Make    Model  Year
0    Y163O8161RUS     2.0  3200.0     Ford    Focus  2006
1     E432XX77RUS     1.0  6500.0   Toyota    Camry  2019
2     7184TT36RUS     1.0  2100.0     Ford    Focus  1983
3    X582HE161RUS     2.0  2000.0     Ford    Focus  2009
4    92918M178RUS     1.0  5700.0     Ford    Focus  1989
..            ...     ...     ...      ...      ...   ...
925       QW12345     1.5  1500.0    Honda    Civic  2007
926       ZX67890     2.0  3000.0   Nissan   Sentra  2006
927       ER23456     0.5   500.0    Mazda        3  2005
928       TY78901     3.0  2000.0  Hyundai  Elantra  1998
929       UI34567     1.0  1000.0      Kia     Soul  2000

[930 rows x 6 columns]

In [185]:
%%timeit
df['Calculated'] = df['Fines'] / df['Refund'] * df['Year']

189 μs ± 5.87 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [186]:
df

        CarNumber  Refund   Fines     Make    Model  Year  Calculated
0    Y163O8161RUS     2.0  3200.0     Ford    Focus  2006   3209600.0
1     E432XX77RUS     1.0  6500.0   Toyota    Camry  2019  13123500.0
2     7184TT36RUS     1.0  2100.0     Ford    Focus  1983   4164300.0
3    X582HE161RUS     2.0  2000.0     Ford    Focus  2009   2009000.0
4    92918M178RUS     1.0  5700.0     Ford    Focus  1989  11337300.0
..            ...     ...     ...      ...      ...   ...         ...
925       QW12345     1.5  1500.0    Honda    Civic  2007   2007000.0
926       ZX67890     2.0  3000.0   Nissan   Sentra  2006   3009000.0
927       ER23456     0.5   500.0    Mazda        3  2005   2005000.0
928       TY78901     3.0  2000.0  Hyundai  Elantra  1998   1332000.0
929       UI34567     1.0  1000.0      Kia     Soul  2000   2000000.0

[930 rows x 7 columns]

## Расчет времени и добавление колонок разными методами

In [187]:
def calc_for_loop(df):
    result = []
    for i in range(len(df)):
        value = df.iloc[i]['Fines'] / df.iloc[i]['Refund'] * df.iloc[i]['Year']
        result.append(value)
    return result

In [188]:
%%timeit
df['calculated_for_loop'] = calc_for_loop(df)

156 ms ± 4.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [189]:
df

,CarNumber,Refund,Fines,Make,Model,Year,Calculated,calculated_for_loop
0,Y163O8161RUS,2.0,3200.0,Ford,Focus,2006,3209600.0,3209600.0
1,E432XX77RUS,1.0,6500.0,Toyota,Camry,2019,13123500.0,13123500.0
2,7184TT36RUS,1.0,2100.0,Ford,Focus,1983,4164300.0,4164300.0
3,X582HE161RUS,2.0,2000.0,Ford,Focus,2009,2009000.0,2009000.0
4,92918M178RUS,1.0,5700.0,Ford,Focus,1989,11337300.0,11337300.0
...,...,...,...,...,...,...,...,...
925,QW12345,1.5,1500.0,Honda,Civic,2007,2007000.0,2007000.0
926,ZX67890,2.0,3000.0,Nissan,Sentra,2006,3009000.0,3009000.0
927,ER23456,0.5,500.0,Mazda,3,2005,2005000.0,2005000.0
928,TY78901,3.0,2000.0,Hyundai,Elantra,1998,1332000.0,1332000.0
929,UI34567,1.0,1000.0,Kia,Soul,2000,2000000.0,2000000.0

In [190]:
def calc_iterrows(df):
    result = []
    for index, row in df.iterrows():
        value = row['Fines'] / row['Refund'] * row['Year']
        result.append(value)
    return result

In [191]:
%%timeit
df['calculated_iterrows'] = calc_iterrows(df)

38 ms ± 459 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [192]:
df

,CarNumber,Refund,Fines,Make,Model,Year,Calculated,calculated_for_loop,calculated_iterrows
0,Y163O8161RUS,2.0,3200.0,Ford,Focus,2006,3209600.0,3209600.0,3209600.0
1,E432XX77RUS,1.0,6500.0,Toyota,Camry,2019,13123500.0,13123500.0,13123500.0
2,7184TT36RUS,1.0,2100.0,Ford,Focus,1983,4164300.0,4164300.0,4164300.0
3,X582HE161RUS,2.0,2000.0,Ford,Focus,2009,2009000.0,2009000.0,2009000.0
4,92918M178RUS,1.0,5700.0,Ford,Focus,1989,11337300.0,11337300.0,11337300.0
...,...,...,...,...,...,...,...,...,...
925,QW12345,1.5,1500.0,Honda,Civic,2007,2007000.0,2007000.0,2007000.0
926,ZX67890,2.0,3000.0,Nissan,Sentra,2006,3009000.0,3009000.0,3009000.0
927,ER23456,0.5,500.0,Mazda,3,2005,2005000.0,2005000.0,2005000.0
928,TY78901,3.0,2000.0,Hyundai,Elantra,1998,1332000.0,1332000.0,1332000.0
929,UI34567,1.0,1000.0,Kia,Soul,2000,2000000.0,2000000.0,2000000.0

In [193]:
%%timeit
df['calculated_apply'] = df.apply(lambda row: row['Fines'] / row['Refund'] * row['Year'], axis=1)

6.56 ms ± 36.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [194]:
df

,CarNumber,Refund,Fines,Make,Model,Year,Calculated,calculated_for_loop,calculated_iterrows,calculated_apply
0,Y163O8161RUS,2.0,3200.0,Ford,Focus,2006,3209600.0,3209600.0,3209600.0,3209600.0
1,E432XX77RUS,1.0,6500.0,Toyota,Camry,2019,13123500.0,13123500.0,13123500.0,13123500.0
2,7184TT36RUS,1.0,2100.0,Ford,Focus,1983,4164300.0,4164300.0,4164300.0,4164300.0
3,X582HE161RUS,2.0,2000.0,Ford,Focus,2009,2009000.0,2009000.0,2009000.0,2009000.0
4,92918M178RUS,1.0,5700.0,Ford,Focus,1989,11337300.0,11337300.0,11337300.0,11337300.0
...,...,...,...,...,...,...,...,...,...,...
925,QW12345,1.5,1500.0,Honda,Civic,2007,2007000.0,2007000.0,2007000.0,2007000.0
926,ZX67890,2.0,3000.0,Nissan,Sentra,2006,3009000.0,3009000.0,3009000.0,3009000.0
927,ER23456,0.5,500.0,Mazda,3,2005,2005000.0,2005000.0,2005000.0,2005000.0
928,TY78901,3.0,2000.0,Hyundai,Elantra,1998,1332000.0,1332000.0,1332000.0,1332000.0
929,UI34567,1.0,1000.0,Kia,Soul,2000,2000000.0,2000000.0,2000000.0,2000000.0

In [195]:
%%timeit
fines_series = df['Fines']
refund_series = df['Refund']
year_series = df['Year']
df['calculated_series'] = (fines_series / refund_series) * year_series

178 μs ± 1.93 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [196]:
df

,CarNumber,Refund,Fines,Make,Model,Year,Calculated,calculated_for_loop,calculated_iterrows,calculated_apply,calculated_series
0,Y163O8161RUS,2.0,3200.0,Ford,Focus,2006,3209600.0,3209600.0,3209600.0,3209600.0,3209600.0
1,E432XX77RUS,1.0,6500.0,Toyota,Camry,2019,13123500.0,13123500.0,13123500.0,13123500.0,13123500.0
2,7184TT36RUS,1.0,2100.0,Ford,Focus,1983,4164300.0,4164300.0,4164300.0,4164300.0,4164300.0
3,X582HE161RUS,2.0,2000.0,Ford,Focus,2009,2009000.0,2009000.0,2009000.0,2009000.0,2009000.0
4,92918M178RUS,1.0,5700.0,Ford,Focus,1989,11337300.0,11337300.0,11337300.0,11337300.0,11337300.0
...,...,...,...,...,...,...,...,...,...,...,...
925,QW12345,1.5,1500.0,Honda,Civic,2007,2007000.0,2007000.0,2007000.0,2007000.0,2007000.0
926,ZX67890,2.0,3000.0,Nissan,Sentra,2006,3009000.0,3009000.0,3009000.0,3009000.0,3009000.0
927,ER23456,0.5,500.0,Mazda,3,2005,2005000.0,2005000.0,2005000.0,2005000.0,2005000.0
928,TY78901,3.0,2000.0,Hyundai,Elantra,1998,1332000.0,1332000.0,1332000.0,1332000.0,1332000.0
929,UI34567,1.0,1000.0,Kia,Soul,2000,2000000.0,2000000.0,2000000.0,2000000.0,2000000.0

In [197]:
%%timeit
values_fines = df['Fines'].values
values_refund = df['Refund'].values
values_year = df['Year'].values
df['calculated_values'] = (values_fines / values_refund) * values_year

94.4 μs ± 278 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [198]:
df

,CarNumber,Refund,Fines,Make,Model,Year,Calculated,calculated_for_loop,calculated_iterrows,calculated_apply,calculated_series,calculated_values
0,Y163O8161RUS,2.0,3200.0,Ford,Focus,2006,3209600.0,3209600.0,3209600.0,3209600.0,3209600.0,3209600.0
1,E432XX77RUS,1.0,6500.0,Toyota,Camry,2019,13123500.0,13123500.0,13123500.0,13123500.0,13123500.0,13123500.0
2,7184TT36RUS,1.0,2100.0,Ford,Focus,1983,4164300.0,4164300.0,4164300.0,4164300.0,4164300.0,4164300.0
3,X582HE161RUS,2.0,2000.0,Ford,Focus,2009,2009000.0,2009000.0,2009000.0,2009000.0,2009000.0,2009000.0
4,92918M178RUS,1.0,5700.0,Ford,Focus,1989,11337300.0,11337300.0,11337300.0,11337300.0,11337300.0,11337300.0
...,...,...,...,...,...,...,...,...,...,...,...,...
925,QW12345,1.5,1500.0,Honda,Civic,2007,2007000.0,2007000.0,2007000.0,2007000.0,2007000.0,2007000.0
926,ZX67890,2.0,3000.0,Nissan,Sentra,2006,3009000.0,3009000.0,3009000.0,3009000.0,3009000.0,3009000.0
927,ER23456,0.5,500.0,Mazda,3,2005,2005000.0,2005000.0,2005000.0,2005000.0,2005000.0,2005000.0
928,TY78901,3.0,2000.0,Hyundai,Elantra,1998,1332000.0,1332000.0,1332000.0,1332000.0,1332000.0,1332000.0
929,UI34567,1.0,1000.0,Kia,Soul,2000,2000000.0,2000000.0,2000000.0,2000000.0,2000000.0,2000000.0

In [199]:
%%timeit
row = df[df['CarNumber'] == '92918M178RUS']

438 μs ± 1.87 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [200]:
df.set_index('CarNumber', inplace=True)

In [201]:
df

,Refund,Fines,Make,Model,Year,Calculated,calculated_for_loop,calculated_iterrows,calculated_apply,calculated_series,calculated_values
CarNumber,,,,,,,,,,,
Y163O8161RUS,2.0,3200.0,Ford,Focus,2006,3209600.0,3209600.0,3209600.0,3209600.0,3209600.0,3209600.0
E432XX77RUS,1.0,6500.0,Toyota,Camry,2019,13123500.0,13123500.0,13123500.0,13123500.0,13123500.0,13123500.0
7184TT36RUS,1.0,2100.0,Ford,Focus,1983,4164300.0,4164300.0,4164300.0,4164300.0,4164300.0,4164300.0
X582HE161RUS,2.0,2000.0,Ford,Focus,2009,2009000.0,2009000.0,2009000.0,2009000.0,2009000.0,2009000.0
92918M178RUS,1.0,5700.0,Ford,Focus,1989,11337300.0,11337300.0,11337300.0,11337300.0,11337300.0,11337300.0
...,...,...,...,...,...,...,...,...,...,...,...
QW12345,1.5,1500.0,Honda,Civic,2007,2007000.0,2007000.0,2007000.0,2007000.0,2007000.0,2007000.0
ZX67890,2.0,3000.0,Nissan,Sentra,2006,3009000.0,3009000.0,3009000.0,3009000.0,3009000.0,3009000.0
ER23456,0.5,500.0,Mazda,3,2005,2005000.0,2005000.0,2005000.0,2005000.0,2005000.0,2005000.0
TY78901,3.0,2000.0,Hyundai,Elantra,1998,1332000.0,1332000.0,1332000.0,1332000.0,1332000.0,1332000.0
UI34567,1.0,1000.0,Kia,Soul,2000,2000000.0,2000000.0,2000000.0,2000000.0,2000000.0,2000000.0

In [202]:
%%timeit
row = df.loc['92918M178RUS']

222 μs ± 4.46 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [203]:
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
Index: 930 entries, Y163O8161RUS to UI34567
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Refund               930 non-null    float64
 1   Fines                930 non-null    float64
 2   Make                 930 non-null    str
 3   Model                919 non-null    str
 4   Year                 930 non-null    int64
 5   Calculated           930 non-null    float64
 6   calculated_for_loop  930 non-null    float64
 7   calculated_iterrows  930 non-null    float64
 8   calculated_apply     930 non-null    float64
 9   calculated_series    930 non-null    float64
 10  calculated_values    930 non-null    float64
dtypes: float64(8), int64(1), str(2)
memory usage: 250.6 KB

In [204]:
optimized_df = df.copy()

In [205]:
optimized_df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
Index: 930 entries, Y163O8161RUS to UI34567
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Refund               930 non-null    float64
 1   Fines                930 non-null    float64
 2   Make                 930 non-null    str
 3   Model                919 non-null    str
 4   Year                 930 non-null    int64
 5   Calculated           930 non-null    float64
 6   calculated_for_loop  930 non-null    float64
 7   calculated_iterrows  930 non-null    float64
 8   calculated_apply     930 non-null    float64
 9   calculated_series    930 non-null    float64
 10  calculated_values    930 non-null    float64
dtypes: float64(8), int64(1), str(2)
memory usage: 250.6 KB

In [206]:
for col in optimized_df.select_dtypes(include=['float64']).columns:
    optimized_df[col] = pd.to_numeric(optimized_df[col], downcast='float')

In [207]:
for col in optimized_df.select_dtypes(include=['int64']).columns:
    optimized_df[col] = pd.to_numeric(optimized_df[col], downcast='integer')

In [208]:
optimized_df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
Index: 930 entries, Y163O8161RUS to UI34567
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Refund               930 non-null    float32
 1   Fines                930 non-null    float32
 2   Make                 930 non-null    str
 3   Model                919 non-null    str
 4   Year                 930 non-null    int16
 5   Calculated           930 non-null    float64
 6   calculated_for_loop  930 non-null    float64
 7   calculated_iterrows  930 non-null    float64
 8   calculated_apply     930 non-null    float64
 9   calculated_series    930 non-null    float64
 10  calculated_values    930 non-null    float64
dtypes: float32(2), float64(6), int16(1), str(2)
memory usage: 237.9 KB

In [209]:
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].astype('category')

/var/folders/zz/zyxvpxvq6csfxvn_n00lv7p804ysxk/T/ipykernel_42274/3068368952.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=['object']).columns:

In [210]:
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
Index: 930 entries, Y163O8161RUS to UI34567
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Refund               930 non-null    float64
 1   Fines                930 non-null    float64
 2   Make                 930 non-null    category
 3   Model                919 non-null    category
 4   Year                 930 non-null    int64
 5   Calculated           930 non-null    float64
 6   calculated_for_loop  930 non-null    float64
 7   calculated_iterrows  930 non-null    float64
 8   calculated_apply     930 non-null    float64
 9   calculated_series    930 non-null    float64
 10  calculated_values    930 non-null    float64
dtypes: category(2), float64(8), int64(1)
memory usage: 156.1 KB

In [211]:
gc.collect()

6