In [31]:
import pandas as pd

## Импорт + считывание и заданеие индексов

In [32]:
cars = pd.read_csv("auto.csv")

In [33]:
cars

      ID     CarNumber    Make_n_model  Refund    Fines  History
0      0  Y163O8161RUS      Ford Focus     2.0   3200.0      NaN
1      1   E432XX77RUS    Toyota Camry     1.0   6500.0      NaN
2      2   7184TT36RUS      Ford Focus     1.0   2100.0      NaN
3      3  X582HE161RUS      Ford Focus     2.0   2000.0      NaN
4      4  E34877152RUS      Ford Focus     2.0   6100.0      NaN
..   ...           ...             ...     ...      ...      ...
926  926  Y163O8161RUS      Ford Focus     2.0   1600.0      NaN
927  927  M0309X197RUS      Ford Focus     1.0  22300.0      NaN
928  928  O673E8197RUS      Ford Focus     2.0    600.0      NaN
929  929  8610T8154RUS      Ford Focus     1.0   2000.0      NaN
930  930  H419XE197RUS  Toyota Corolla     2.0      NaN      2.0

[931 rows x 6 columns]

In [34]:
# Предположим, есть столбец 'user' или 'ID'
cars = cars.set_index('ID')  # заменит текущий индекс на столбец 'user'

In [35]:
cars

        CarNumber    Make_n_model  Refund    Fines  History
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0      NaN
1     E432XX77RUS    Toyota Camry     1.0   6500.0      NaN
2     7184TT36RUS      Ford Focus     1.0   2100.0      NaN
3    X582HE161RUS      Ford Focus     2.0   2000.0      NaN
4    E34877152RUS      Ford Focus     2.0   6100.0      NaN
..            ...             ...     ...      ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0      NaN
927  M0309X197RUS      Ford Focus     1.0  22300.0      NaN
928  O673E8197RUS      Ford Focus     2.0    600.0      NaN
929  8610T8154RUS      Ford Focus     1.0   2000.0      NaN
930  H419XE197RUS  Toyota Corolla     2.0      NaN      2.0

[931 rows x 5 columns]

In [36]:
print(cars.count())

CarNumber       931
Make_n_model    931
Refund          914
Fines           869
History          82
dtype: int64

## Удаление дубликатов и проверки

In [37]:
# Удаляем дубликаты, учитывая только указанные столбцы, оставляя последние
cars = cars.drop_duplicates(subset=['CarNumber', 'Make_n_model', 'Fines'], keep='last')

In [38]:

# Проверяем число наблюдений
print(f"Количество наблюдений после удаления дубликатов: {cars.count()}")

Количество наблюдений после удаления дубликатов: CarNumber       725
Make_n_model    725
Refund          713
Fines           665
History          65
dtype: int64

In [39]:
cars

        CarNumber    Make_n_model  Refund    Fines  History
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0      NaN
1     E432XX77RUS    Toyota Camry     1.0   6500.0      NaN
2     7184TT36RUS      Ford Focus     1.0   2100.0      NaN
3    X582HE161RUS      Ford Focus     2.0   2000.0      NaN
5    92918M178RUS      Ford Focus     1.0   5700.0      NaN
..            ...             ...     ...      ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0      NaN
927  M0309X197RUS      Ford Focus     1.0  22300.0      NaN
928  O673E8197RUS      Ford Focus     2.0    600.0      NaN
929  8610T8154RUS      Ford Focus     1.0   2000.0      NaN
930  H419XE197RUS  Toyota Corolla     2.0      NaN      2.0

[725 rows x 5 columns]

In [40]:
print(cars.isnull().sum())

CarNumber         0
Make_n_model      0
Refund           12
Fines            60
History         660
dtype: int64

In [41]:
# Количество строк в DataFrame
n_rows = len(cars)

# Минимальное количество непустых значений для сохранения столбца
min_non_nulls = n_rows - 500

# Удаляем столбцы с более чем 500 пропущенными значениями
cars = cars.dropna(axis=1, thresh=min_non_nulls)

In [42]:
cars

        CarNumber    Make_n_model  Refund    Fines
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0
1     E432XX77RUS    Toyota Camry     1.0   6500.0
2     7184TT36RUS      Ford Focus     1.0   2100.0
3    X582HE161RUS      Ford Focus     2.0   2000.0
5    92918M178RUS      Ford Focus     1.0   5700.0
..            ...             ...     ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0
927  M0309X197RUS      Ford Focus     1.0  22300.0
928  O673E8197RUS      Ford Focus     2.0    600.0
929  8610T8154RUS      Ford Focus     1.0   2000.0
930  H419XE197RUS  Toyota Corolla     2.0      NaN

[725 rows x 4 columns]

In [43]:
print(cars.isnull().sum())

CarNumber        0
Make_n_model     0
Refund          12
Fines           60
dtype: int64

In [44]:
cars['Refund'] = cars['Refund'].ffill()

In [45]:
print(cars.isnull().sum())

CarNumber        0
Make_n_model     0
Refund           0
Fines           60
dtype: int64

In [46]:
cars

        CarNumber    Make_n_model  Refund    Fines
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0
1     E432XX77RUS    Toyota Camry     1.0   6500.0
2     7184TT36RUS      Ford Focus     1.0   2100.0
3    X582HE161RUS      Ford Focus     2.0   2000.0
5    92918M178RUS      Ford Focus     1.0   5700.0
..            ...             ...     ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0
927  M0309X197RUS      Ford Focus     1.0  22300.0
928  O673E8197RUS      Ford Focus     2.0    600.0
929  8610T8154RUS      Ford Focus     1.0   2000.0
930  H419XE197RUS  Toyota Corolla     2.0      NaN

[725 rows x 4 columns]

In [47]:
mean_fines = cars['Fines'].mean()
cars['Fines'] = cars['Fines'].fillna(mean_fines)

In [48]:
print(cars.isnull().sum())

CarNumber       0
Make_n_model    0
Refund          0
Fines           0
dtype: int64

In [49]:
cars

        CarNumber    Make_n_model  Refund         Fines
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.000000
1     E432XX77RUS    Toyota Camry     1.0   6500.000000
2     7184TT36RUS      Ford Focus     1.0   2100.000000
3    X582HE161RUS      Ford Focus     2.0   2000.000000
5    92918M178RUS      Ford Focus     1.0   5700.000000
..            ...             ...     ...           ...
926  Y163O8161RUS      Ford Focus     2.0   1600.000000
927  M0309X197RUS      Ford Focus     1.0  22300.000000
928  O673E8197RUS      Ford Focus     2.0    600.000000
929  8610T8154RUS      Ford Focus     1.0   2000.000000
930  H419XE197RUS  Toyota Corolla     2.0   8594.586466

[725 rows x 4 columns]

In [50]:
def split_make_model(x):
    parts = x.split(' ', 1)
    if len(parts) == 2:
        return parts
    else:
        return [parts[0], '']

cars['Make'], cars['Model'] = zip(*cars['Make_n_model'].apply(split_make_model))

In [51]:
cars

        CarNumber    Make_n_model  Refund         Fines    Make    Model
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.000000    Ford    Focus
1     E432XX77RUS    Toyota Camry     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS      Ford Focus     1.0   2100.000000    Ford    Focus
3    X582HE161RUS      Ford Focus     2.0   2000.000000    Ford    Focus
5    92918M178RUS      Ford Focus     1.0   5700.000000    Ford    Focus
..            ...             ...     ...           ...     ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.000000    Ford    Focus
927  M0309X197RUS      Ford Focus     1.0  22300.000000    Ford    Focus
928  O673E8197RUS      Ford Focus     2.0    600.000000    Ford    Focus
929  8610T8154RUS      Ford Focus     1.0   2000.000000    Ford    Focus
930  H419XE197RUS  Toyota Corolla     2.0   8594.586466  Toyota  Corolla

[725 rows x 6 columns]

In [52]:
# 2. Удаляем исходный столбец
cars = cars.drop(columns=['Make_n_model'])

In [53]:
cars

        CarNumber  Refund         Fines    Make    Model
ID
0    Y163O8161RUS     2.0   3200.000000    Ford    Focus
1     E432XX77RUS     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS     1.0   2100.000000    Ford    Focus
3    X582HE161RUS     2.0   2000.000000    Ford    Focus
5    92918M178RUS     1.0   5700.000000    Ford    Focus
..            ...     ...           ...     ...      ...
926  Y163O8161RUS     2.0   1600.000000    Ford    Focus
927  M0309X197RUS     1.0  22300.000000    Ford    Focus
928  O673E8197RUS     2.0    600.000000    Ford    Focus
929  8610T8154RUS     1.0   2000.000000    Ford    Focus
930  H419XE197RUS     2.0   8594.586466  Toyota  Corolla

[725 rows x 5 columns]

In [54]:
cars.to_json('auto.json', orient='records')

In [55]:
df2 = pd.read_json("auto.json", orient = 'records')

In [56]:
df2

        CarNumber  Refund         Fines    Make    Model
0    Y163O8161RUS       2   3200.000000    Ford    Focus
1     E432XX77RUS       1   6500.000000  Toyota    Camry
2     7184TT36RUS       1   2100.000000    Ford    Focus
3    X582HE161RUS       2   2000.000000    Ford    Focus
4    92918M178RUS       1   5700.000000    Ford    Focus
..            ...     ...           ...     ...      ...
720  Y163O8161RUS       2   1600.000000    Ford    Focus
721  M0309X197RUS       1  22300.000000    Ford    Focus
722  O673E8197RUS       2    600.000000    Ford    Focus
723  8610T8154RUS       1   2000.000000    Ford    Focus
724  H419XE197RUS       2   8594.586466  Toyota  Corolla

[725 rows x 5 columns]

In [57]:
df2.count()

CarNumber    725
Refund       725
Fines        725
Make         725
Model        725
dtype: int64

In [58]:
df2['Fines'].mean()

np.float64(8594.586466165412)

In [59]:
df2['Refund'].mean()

np.float64(1.5172413793103448)