In [1]:
import pandas as pd

## Импорт, задание .2 формата, считывание и задание индекса

In [2]:
pd.options.display.float_format = '{:.2f}'.format

In [3]:
auto_ex02 = pd.read_json('auto.json')

In [4]:
auto_ex02

        CarNumber  Refund    Fines    Make    Model
0    Y163O8161RUS       2  3200.00    Ford    Focus
1     E432XX77RUS       1  6500.00  Toyota    Camry
2     7184TT36RUS       1  2100.00    Ford    Focus
3    X582HE161RUS       2  2000.00    Ford    Focus
4    92918M178RUS       1  5700.00    Ford    Focus
..            ...     ...      ...     ...      ...
720  Y163O8161RUS       2  1600.00    Ford    Focus
721  M0309X197RUS       1 22300.00    Ford    Focus
722  O673E8197RUS       2   600.00    Ford    Focus
723  8610T8154RUS       1  2000.00    Ford    Focus
724  H419XE197RUS       2  8594.59  Toyota  Corolla

[725 rows x 5 columns]

In [5]:
auto_ex02 = auto_ex02.set_index('CarNumber')

In [6]:
auto_ex02

              Refund    Fines    Make    Model
CarNumber
Y163O8161RUS       2  3200.00    Ford    Focus
E432XX77RUS        1  6500.00  Toyota    Camry
7184TT36RUS        1  2100.00    Ford    Focus
X582HE161RUS       2  2000.00    Ford    Focus
92918M178RUS       1  5700.00    Ford    Focus
...              ...      ...     ...      ...
Y163O8161RUS       2  1600.00    Ford    Focus
M0309X197RUS       1 22300.00    Ford    Focus
O673E8197RUS       2   600.00    Ford    Focus
8610T8154RUS       1  2000.00    Ford    Focus
H419XE197RUS       2  8594.59  Toyota  Corolla

[725 rows x 4 columns]

## Выводы по проверкам

In [7]:
fines_more_2100 = auto_ex02[auto_ex02['Fines'] > 2100]

In [8]:
fines_more_2100_and_refound_equals_2 = fines_more_2100[fines_more_2100["Refund"] == 2]

In [9]:
print("fines are greater than 2100:")
print(fines_more_2100)

fines are greater than 2100:
              Refund    Fines        Make    Model
CarNumber
Y163O8161RUS       2  3200.00        Ford    Focus
E432XX77RUS        1  6500.00      Toyota    Camry
92918M178RUS       1  5700.00        Ford    Focus
H234YH197RUS       2  6000.00        Ford    Focus
E40577152RUS       1  8594.59        Ford    Focus
...              ...      ...         ...      ...
O718MM163RUS       2  8594.59        Ford    Focus
7065C8197RUS       2 11400.00  Volkswagen   Passat
O22097197RUS       1 24300.00        Ford    Focus
M0309X197RUS       1 22300.00        Ford    Focus
H419XE197RUS       2  8594.59      Toyota  Corolla

[455 rows x 4 columns]

In [10]:
print("fines are greater than 2100 and refunds are equal 2:")
print(fines_more_2100_and_refound_equals_2)

fines are greater than 2100 and refunds are equal 2:
              Refund    Fines        Make    Model
CarNumber
Y163O8161RUS       2  3200.00        Ford    Focus
H234YH197RUS       2  6000.00        Ford    Focus
707987163RUS       2  2200.00        Ford    Focus
K330T8197RUS       2  8200.00       Skoda  Octavia
M592CH197RUS       2  8594.59       Skoda  Octavia
...              ...      ...         ...      ...
O136HO197RUS       2  7800.00      Toyota  Corolla
O68897197RUS       2 12300.00        Ford    Focus
O718MM163RUS       2  8594.59        Ford    Focus
7065C8197RUS       2 11400.00  Volkswagen   Passat
H419XE197RUS       2  8594.59      Toyota  Corolla

[309 rows x 4 columns]

In [11]:
print("The rows where the models are from the list: ['Focus', 'Corolla']:")

# Используем .isin() для проверки, входит ли значение в список
print(auto_ex02[auto_ex02["Model"].isin(["Focus", "Corolla"])])

The rows where the models are from the list: ['Focus', 'Corolla']:
              Refund    Fines    Make    Model
CarNumber
Y163O8161RUS       2  3200.00    Ford    Focus
7184TT36RUS        1  2100.00    Ford    Focus
X582HE161RUS       2  2000.00    Ford    Focus
92918M178RUS       1  5700.00    Ford    Focus
H234YH197RUS       2  6000.00    Ford    Focus
...              ...      ...     ...      ...
Y163O8161RUS       2  1600.00    Ford    Focus
M0309X197RUS       1 22300.00    Ford    Focus
O673E8197RUS       2   600.00    Ford    Focus
8610T8154RUS       1  2000.00    Ford    Focus
H419XE197RUS       2  8594.59  Toyota  Corolla

[593 rows x 4 columns]

In [12]:
print("The rows where the car number is from the list: ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']")

car_numbers = ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']
print(auto_ex02.loc[auto_ex02.index.isin(car_numbers)])

The rows where the car number is from the list: ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']
              Refund     Fines  Make  Model
CarNumber
92928M178RUS       1   8594.59  Ford  Focus
H115YO163RUS       1   2200.00  Ford  Focus
7788KT197RUS       2  12000.00  Ford  Focus
X758HY197RUS       2  24200.00  Ford  Focus
X758HY197RUS       2  72600.00  Ford  Focus
Y7689C197RUS       1  27000.00  Ford  Focus
92928M178RUS       1    600.00  Ford  Focus
H115YO163RUS       1   8594.59  Ford  Focus
H115YO163RUS       2   1100.00  Ford  Focus
7788KT197RUS       2   8594.59  Ford  Focus
7788KT197RUS       1  20000.00  Ford  Focus
X758HY197RUS       2 145200.00  Ford  Focus
92928M178RUS       1   1200.00  Ford  Focus
Y7689C197RUS       2   9000.00  Ford  Focus
Y7689C197RUS       2  45000.00  Ford  Focus
7788KT197RUS       2   4000.00  Ford  Focus
Y7689C197RUS       1  36000.00  Ford  Focus
92928M178RUS       2   3000.00  Ford  Focus

## Группировка

In [13]:
auto_ex02.groupby('Make')['Fines'].median()

Make
Audi         4200.00
BMW          6500.00
Ford         3500.00
Skoda        3250.00
Toyota       7700.00
Volkswagen   4300.00
Volvo        8500.00
Name: Fines, dtype: float64

In [14]:
auto_ex02.groupby(['Make', 'Model'])['Fines'].median()

Make        Model
Audi                  4200.00
BMW                   6500.00
Ford        Focus     3500.00
            Mondeo    7650.00
Skoda       Octavia   3250.00
Toyota      Camry     7700.00
            Corolla   7700.00
Volkswagen            7400.00
            Golf      4800.00
            Jetta     2800.00
            Passat    3500.00
            Touareg   5800.00
Volvo                 8500.00
Name: Fines, dtype: float64

In [15]:
auto_ex02.groupby(['Make', 'Model'])['Fines'].count()

Make        Model
Audi                     1
BMW                      3
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen               3
            Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Volvo                    2
Name: Fines, dtype: int64

In [16]:
auto_ex02.groupby(['Make', 'Model'])['Fines'].min()
auto_ex02.groupby(['Make', 'Model'])['Fines'].max()

Make        Model
Audi                    4200.00
BMW                     8594.59
Ford        Focus     180000.00
            Mondeo     46200.00
Skoda       Octavia   145000.00
Toyota      Camry      22400.00
            Corolla    34300.00
Volkswagen              7900.00
            Golf      168000.00
            Jetta      46000.00
            Passat     29700.00
            Touareg     8594.59
Volvo                  10200.00
Name: Fines, dtype: float64

In [17]:
auto_ex02.groupby(['Make', 'Model'])['Fines'].std()

Make        Model
Audi                       NaN
BMW                    2826.56
Ford        Focus     15041.27
            Mondeo    18987.33
Skoda       Octavia   24339.74
Toyota      Camry      6410.25
            Corolla    9629.33
Volkswagen             3674.69
            Golf      36950.84
            Jetta     17743.03
            Passat     6969.74
            Touareg    3461.78
Volvo                  2404.16
Name: Fines, dtype: float64

In [18]:
fines_counts = auto_ex02.index.value_counts().sort_values(ascending=False)
print(fines_counts)

CarNumber
92928M178RUS    4
7788KT197RUS    4
Y7689C197RUS    4
92918M178RUS    3
7830C8197RUS    3
               ..
O136HO197RUS    1
O22097197RUS    1
M0309X197RUS    1
O673E8197RUS    1
8610T8154RUS    1
Name: count, Length: 531, dtype: int64

In [19]:
sum_fines_by_car = auto_ex02.groupby(auto_ex02.index)['Fines'].sum().sort_values(ascending=False)
print(sum_fines_by_car)

CarNumber
X758HY197RUS   242000.00
9020YC197RUS   217500.00
M0279X197RUS   216000.00
Y352O8197RUS   207200.00
Y778EE197RUS   192000.00
                  ...
Y166O8161RUS      100.00
K326T8197RUS      100.00
Y195O8161RUS      100.00
C58078163RUS      100.00
705787163RUS      100.00
Name: Fines, Length: 531, dtype: float64

In [20]:
top_car_by_fines = sum_fines_by_car.index[0]
top_rows_by_fines = auto_ex02.loc[top_car_by_fines]
print(top_rows_by_fines)

              Refund     Fines  Make  Model
CarNumber
X758HY197RUS       2  24200.00  Ford  Focus
X758HY197RUS       2  72600.00  Ford  Focus
X758HY197RUS       2 145200.00  Ford  Focus

In [21]:
model_counts = auto_ex02.groupby(auto_ex02.index)['Model'].nunique()
multiple_models = model_counts[model_counts > 1]
print(multiple_models)

CarNumber
E316EH197RUS    2
Name: Model, dtype: int64

In [25]:
models = ['Focus', 'Corolla']
auto_ex02.loc[auto_ex02['Model'].isin(models)]

              Refund    Fines    Make    Model
CarNumber
Y163O8161RUS       2  3200.00    Ford    Focus
7184TT36RUS        1  2100.00    Ford    Focus
X582HE161RUS       2  2000.00    Ford    Focus
92918M178RUS       1  5700.00    Ford    Focus
H234YH197RUS       2  6000.00    Ford    Focus
...              ...      ...     ...      ...
Y163O8161RUS       2  1600.00    Ford    Focus
M0309X197RUS       1 22300.00    Ford    Focus
O673E8197RUS       2   600.00    Ford    Focus
8610T8154RUS       1  2000.00    Ford    Focus
H419XE197RUS       2  8594.59  Toyota  Corolla

[593 rows x 4 columns]

In [30]:
auto_ex02.groupby(['Make', 'Model']).agg('Fines').count()

Make        Model
Audi                     1
BMW                      3
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen               3
            Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Volvo                    2
Name: Fines, dtype: int64